# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
    ]
